// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STTproject.Data;

#nullable disable

namespace STTproject.Migrations
{
    [DbContext(typeof(SttprojectContext))]
    [Migration("20260509141059_RedefineCascadeDelete")]
    partial class RedefineCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ojt")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STTproject.Data.CompanyItem", b =>
                {
                    b.Property<int>("CompanyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EffectivityDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PriceIncreasePercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CompanyItemId")
                        .HasName("PK__CompanyI__2A0E983839E2C7B0");

                    b.HasIndex(new[] { "ItemCode" }, "UQ__CompanyI__3ECC0FEA1D5CA35D")
                        .IsUnique();

                    b.ToTable("CompanyItem", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SubDistributorId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D8F7607638");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SubDistributorId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "CustomerCode", "SubDistributorId" }, "UQ_ojt_Customer_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerName", "SubDistributorId" }, "UQ_ojt_Customer_Name")
                        .IsUnique();

                    b.ToTable("Customer", "ojt", t =>
                        {
                            t.HasTrigger("trg_Customer_CascadeDeactivate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("STTproject.Data.CustomerBranch", b =>
                {
                    b.Property<int>("CustomerBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerBranchId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Main");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("CustomerBranchId")
                        .HasName("PK__Customer__6F555BBD71F361FA");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "CustomerId", "BranchName" }, "UQ_CustomerBranch_BranchName_PerCustomer")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "UX_CustomerBranch_Default")
                        .IsUnique()
                        .HasFilter("([IsDefault]=(1))");

                    b.ToTable("CustomerBranch", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.ItemsUom", b =>
                {
                    b.Property<int>("ItemsUomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemsUomId"));

                    b.Property<decimal>("ConversionToBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SubdItemId")
                        .HasColumnType("int");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ItemsUomId")
                        .HasName("PK__ItemsUom__537249573414BFF9");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "SubdItemId", "UomName" }, "UQ_ItemsUom_SubdItem_Uom")
                        .IsUnique();

                    b.HasIndex(new[] { "SubdItemId" }, "UX_ItemsUom_OneBaseUnit")
                        .IsUnique()
                        .HasFilter("([IsBaseUnit]=(1))");

                    b.ToTable("ItemsUom", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.ItemsUomPriceHistory", b =>
                {
                    b.Property<int>("ItemsUomPriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemsUomPriceHistoryId"));

                    b.Property<DateTime>("AppliedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CompanyItemId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EffectivityDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ItemsUomId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PriceIncreasePercent")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ItemsUomPriceHistoryId")
                        .HasName("PK__ItemsUom__4D74DA340C04A45B");

                    b.HasIndex("CompanyItemId");

                    b.HasIndex("ItemsUomId");

                    b.ToTable("ItemsUomPriceHistory", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.SalesInvoice", b =>
                {
                    b.Property<int>("SalesInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesInvoiceId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerBranchId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Invoice", "DF_SalesInvoice_OrderType");

                    b.Property<string>("SalesInvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("SalesInvoiceDate")
                        .HasColumnType("date");

                    b.Property<int>("SubDistributorId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SalesInvoiceId")
                        .HasName("PK__SalesInv__BA05CD1A2B3DB990");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerBranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SubDistributorId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "SalesInvoiceCode" }, "UQ__SalesInv__C94B6607BF057E81")
                        .IsUnique();

                    b.ToTable("SalesInvoice", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.SalesInvoiceItem", b =>
                {
                    b.Property<int>("SalesInvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesInvoiceItemId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ItemsUomId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("SubdItemId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SalesInvoiceItemId")
                        .HasName("PK__SalesInv__BA84EC64DF1C1337");

                    b.HasIndex("ItemsUomId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("SubdItemId");

                    b.ToTable("SalesInvoiceItem", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.SubDistributor", b =>
                {
                    b.Property<int>("SubDistributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubDistributorId"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanySubdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EncoderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubdName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SubDistributorId")
                        .HasName("PK__SubDistr__954B9BCD15E8FA9F");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EncoderId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "CompanySubdCode" }, "UQ_SubDistributor_CompanySubdCode")
                        .IsUnique();

                    b.HasIndex(new[] { "SubdCode" }, "UQ_SubDistributor_SubdCode")
                        .IsUnique();

                    b.ToTable("SubDistributor", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.SubdItem", b =>
                {
                    b.Property<int>("SubdItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubdItemId"));

                    b.Property<int>("CompanyItemId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubDistributorId")
                        .HasColumnType("int");

                    b.Property<string>("SubdItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("SubdItemId")
                        .HasName("PK__SubdItem__873BB656E2CB39D1");

                    b.HasIndex("CompanyItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "SubDistributorId", "SubdItemCode" }, "UQ_SubdItem_SubdId_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "SubDistributorId", "CompanyItemId" }, "UQ_SubdItem_Subd_CompanyItem")
                        .IsUnique();

                    b.ToTable("SubdItem", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CD89976AC");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E421704CE2")
                        .IsUnique();

                    b.ToTable("Users", "ojt");
                });

            modelBuilder.Entity("STTproject.Data.Customer", b =>
                {
                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("CustomerCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Customer_CreatedBy");

                    b.HasOne("STTproject.Data.SubDistributor", "SubDistributor")
                        .WithMany("Customers")
                        .HasForeignKey("SubDistributorId")
                        .IsRequired()
                        .HasConstraintName("FK_Customer_SubDistributor");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("CustomerUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_Customer_UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("SubDistributor");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.CustomerBranch", b =>
                {
                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("CustomerBranchCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_CustomerBranch_CreatedBy");

                    b.HasOne("STTproject.Data.Customer", "Customer")
                        .WithOne("CustomerBranch")
                        .HasForeignKey("STTproject.Data.CustomerBranch", "CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerBranch_Customer");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("CustomerBranchUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_CustomerBranch_UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.ItemsUom", b =>
                {
                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("ItemsUomCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_ItemsUom_CreatedBy");

                    b.HasOne("STTproject.Data.SubdItem", "SubdItem")
                        .WithOne("ItemsUom")
                        .HasForeignKey("STTproject.Data.ItemsUom", "SubdItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemsUom_SubdItemId");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("ItemsUomUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_ItemsUom_UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("SubdItem");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.ItemsUomPriceHistory", b =>
                {
                    b.HasOne("STTproject.Data.CompanyItem", "CompanyItem")
                        .WithMany("ItemsUomPriceHistories")
                        .HasForeignKey("CompanyItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemsUomPriceHistory_CompanyItem");

                    b.HasOne("STTproject.Data.ItemsUom", "ItemsUom")
                        .WithMany("ItemsUomPriceHistories")
                        .HasForeignKey("ItemsUomId")
                        .IsRequired()
                        .HasConstraintName("FK_ItemsUomPriceHistory_ItemsUom");

                    b.Navigation("CompanyItem");

                    b.Navigation("ItemsUom");
                });

            modelBuilder.Entity("STTproject.Data.SalesInvoice", b =>
                {
                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("SalesInvoiceCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_SalesInvoice_CreatedBy");

                    b.HasOne("STTproject.Data.CustomerBranch", "CustomerBranch")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerBranchId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoice_CustomerBranch");

                    b.HasOne("STTproject.Data.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoice_Customer");

                    b.HasOne("STTproject.Data.SubDistributor", "SubDistributor")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("SubDistributorId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoice_SubDistributor");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("SalesInvoiceUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_SalesInvoice_UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("CustomerBranch");

                    b.Navigation("SubDistributor");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.SalesInvoiceItem", b =>
                {
                    b.HasOne("STTproject.Data.ItemsUom", "ItemsUom")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("ItemsUomId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceItem_ItemsUom");

                    b.HasOne("STTproject.Data.SalesInvoice", "SalesInvoice")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("SalesInvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceItem_Invoice");

                    b.HasOne("STTproject.Data.SubdItem", "SubdItem")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("SubdItemId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceItem_SubdItem");

                    b.Navigation("ItemsUom");

                    b.Navigation("SalesInvoice");

                    b.Navigation("SubdItem");
                });

            modelBuilder.Entity("STTproject.Data.SubDistributor", b =>
                {
                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("SubDistributorCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_SubDistributor_CreatedBy");

                    b.HasOne("STTproject.Data.User", "Encoder")
                        .WithMany("SubDistributorEncoders")
                        .HasForeignKey("EncoderId")
                        .HasConstraintName("FK_SubDistributor_User");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("SubDistributorUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_SubDistributor_UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Encoder");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.SubdItem", b =>
                {
                    b.HasOne("STTproject.Data.CompanyItem", "CompanyItem")
                        .WithMany("SubdItems")
                        .HasForeignKey("CompanyItemId")
                        .IsRequired()
                        .HasConstraintName("FK_SubdItem_CompanyItem");

                    b.HasOne("STTproject.Data.User", "CreatedByNavigation")
                        .WithMany("SubdItemCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_SubdItem_CreatedBy");

                    b.HasOne("STTproject.Data.SubDistributor", "SubDistributor")
                        .WithMany("SubdItems")
                        .HasForeignKey("SubDistributorId")
                        .IsRequired()
                        .HasConstraintName("FK_SubdItem_SubDistributor");

                    b.HasOne("STTproject.Data.User", "UpdatedByNavigation")
                        .WithMany("SubdItemUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("FK_SubdItem_UpdatedBy");

                    b.Navigation("CompanyItem");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("SubDistributor");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("STTproject.Data.CompanyItem", b =>
                {
                    b.Navigation("ItemsUomPriceHistories");

                    b.Navigation("SubdItems");
                });

            modelBuilder.Entity("STTproject.Data.Customer", b =>
                {
                    b.Navigation("CustomerBranch");

                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("STTproject.Data.CustomerBranch", b =>
                {
                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("STTproject.Data.ItemsUom", b =>
                {
                    b.Navigation("ItemsUomPriceHistories");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("STTproject.Data.SalesInvoice", b =>
                {
                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("STTproject.Data.SubDistributor", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("SalesInvoices");

                    b.Navigation("SubdItems");
                });

            modelBuilder.Entity("STTproject.Data.SubdItem", b =>
                {
                    b.Navigation("ItemsUom");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("STTproject.Data.User", b =>
                {
                    b.Navigation("CustomerBranchCreatedByNavigations");

                    b.Navigation("CustomerBranchUpdatedByNavigations");

                    b.Navigation("CustomerCreatedByNavigations");

                    b.Navigation("CustomerUpdatedByNavigations");

                    b.Navigation("ItemsUomCreatedByNavigations");

                    b.Navigation("ItemsUomUpdatedByNavigations");

                    b.Navigation("SalesInvoiceCreatedByNavigations");

                    b.Navigation("SalesInvoiceUpdatedByNavigations");

                    b.Navigation("SubDistributorCreatedByNavigations");

                    b.Navigation("SubDistributorEncoders");

                    b.Navigation("SubDistributorUpdatedByNavigations");

                    b.Navigation("SubdItemCreatedByNavigations");

                    b.Navigation("SubdItemUpdatedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
