// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STTproject.Data;

#nullable disable

namespace STTproject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419143721_MakePricePerPieceComputed")]
    partial class MakePricePerPieceComputed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STTproject.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("STTproject.Models.SalesInvoice", b =>
                {
                    b.Property<int>("SalesInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesInvoiceId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesInvoiceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SalesInvoiceDate")
                        .HasColumnType("date");

                    b.Property<int>("SubDistributorId")
                        .HasColumnType("int");

                    b.HasKey("SalesInvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SubDistributorId");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("STTproject.Models.SalesInvoiceItem", b =>
                {
                    b.Property<int>("SalesInvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesInvoiceItemId"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesInvoiceId1")
                        .HasColumnType("int");

                    b.Property<int>("SubdItemId")
                        .HasColumnType("int");

                    b.HasKey("SalesInvoiceItemId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("SalesInvoiceId1");

                    b.HasIndex("SubdItemId");

                    b.ToTable("SalesInvoiceItems");
                });

            modelBuilder.Entity("STTproject.Models.SubDistributor", b =>
                {
                    b.Property<int>("SubDistributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubDistributorId"));

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubdCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubDistributorId");

                    b.ToTable("SubDistributors");
                });

            modelBuilder.Entity("STTproject.Models.SubdItem", b =>
                {
                    b.Property<int>("SubdItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubdItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PricePerPiece")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerPiece")
                        .HasColumnType("int");

                    b.Property<int>("SubDistributorId")
                        .HasColumnType("int");

                    b.Property<string>("SubdItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubdItemId");

                    b.HasIndex("SubDistributorId");

                    b.ToTable("SubdItems");
                });

            modelBuilder.Entity("STTproject.Models.SalesInvoice", b =>
                {
                    b.HasOne("STTproject.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STTproject.Models.SubDistributor", "SubDistributor")
                        .WithMany()
                        .HasForeignKey("SubDistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SubDistributor");
                });

            modelBuilder.Entity("STTproject.Models.SalesInvoiceItem", b =>
                {
                    b.HasOne("STTproject.Models.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STTproject.Models.SalesInvoice", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceId1");

                    b.HasOne("STTproject.Models.SubdItem", "SubdItem")
                        .WithMany()
                        .HasForeignKey("SubdItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesInvoice");

                    b.Navigation("SubdItem");
                });

            modelBuilder.Entity("STTproject.Models.SubdItem", b =>
                {
                    b.HasOne("STTproject.Models.SubDistributor", "SubDistributor")
                        .WithMany()
                        .HasForeignKey("SubDistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDistributor");
                });

            modelBuilder.Entity("STTproject.Models.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
